accounts/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.SignupView.as_view(), name="signup"),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    # path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # path('<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    # path('<str:username>/follow/', views.FollowView.as_view(), name='follow'),
    # path('<str:username>/unfollow/', views.UnFollowView, name='unfollow'),
    # path('<str:username>/following_list/', views.FollowingListView.as_view(), name='following_list'),
    # path('<str:username>/follower_list/', views.FollowerListView.as_view(), name='follower_list'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    # path('create/', views.TweetCreateView.as_view(), name='create'),
    # path('<int:pk>/', views.TweetDetailView.as_view(), name='detail'),
    # path('<int:pk>/delete/', views.TweetDeleteView.as_view(), name='delete'),
    # path('<int:pk>/like/', views.LikeView, name='like'),
    # path('<int:pk>/unlike/', views.UnlikeView, name='unlike'),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.WelcomeView.as_view(), name="welcome"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField()

tweets/models.py
# from django.db import models


# class Tweet(models.Model):

welcome/models.py
# from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")

accounts/views.py
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import SignupForm


class SignupView(CreateView):
    form_class = SignupForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("tweets:home")

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password1"]
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        return response

tweets/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "tweets/home.html"

welcome/views.py
from django.views.generic import TemplateView


class WelcomeView(TemplateView):
    template_name = "welcome/welcome.html"

templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %} ← titleを入れる

{% block content %}
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit">ユーザー登録</button>
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}Twitter Clone{% endblock %}</title>
</head>

<body>
  <!-- header  -->
  <header class="mb-3">
    <nav>
      <ul>
        <li><a href="{% url 'welcome:welcome' %}">Twitter Clone</a></li>
        <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
      </ul>
    </nav>
  </header>
  <!-- /header  -->

  <!-- main  -->
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <!-- /main  -->
</body>

</html>

templates/tweets/home.html
{% extends "base.html" %} ← base.htmlを継承

{% block title %}Home{% endblock %} ← titleを入れる

{% block content %}
<h1>Homeです</h1>
{% endblock %}

templates/welcome/welcome.html
{% extends "base.html" %}